// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repositery

import (
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID        uuid.UUID  `json:"id"`
	UserID    int64      `json:"user_id"`
	CreatedAt *time.Time `json:"created_at"`
	ExpiresAt time.Time  `json:"expires_at"`
}

type User struct {
	ID           int64      `json:"id"`
	Email        string     `json:"email"`
	PasswordHash string     `json:"password_hash"`
	CreatedAt    *time.Time `json:"created_at"`
}
