// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package repositery

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
WITH new_project AS (
    INSERT INTO projects (name)
    VALUES ($1)
    RETURNING id, name, created_at, updated_at
)
INSERT INTO project_members (project_id, user_id, role)
SELECT 
    np.id,
    $2,
    'owner'
FROM new_project np
RETURNING id, project_id, user_id, role, created_at
`

type CreateProjectParams struct {
	Name   string `json:"name"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Name, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT 
    p.id AS project_id,
    p.id, p.name, p.created_at, p.updated_at,
    pm.id AS member_id,
    pm.id, pm.project_id, pm.user_id, pm.role, pm.created_at
FROM projects p
JOIN project_members pm 
    ON pm.project_id = p.id
WHERE p.id = $1
  AND pm.user_id = $2
`

type GetProjectByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type GetProjectByIDRow struct {
	ProjectID   int64            `json:"project_id"`
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	MemberID    int64            `json:"member_id"`
	ID_2        int64            `json:"id_2"`
	ProjectID_2 int64            `json:"project_id_2"`
	UserID      int64            `json:"user_id"`
	Role        ProjectRole      `json:"role"`
	CreatedAt_2 pgtype.Timestamp `json:"created_at_2"`
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (GetProjectByIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ID, arg.UserID)
	var i GetProjectByIDRow
	err := row.Scan(
		&i.ProjectID,
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemberID,
		&i.ID_2,
		&i.ProjectID_2,
		&i.UserID,
		&i.Role,
		&i.CreatedAt_2,
	)
	return i, err
}

const getProjectsByUserID = `-- name: GetProjectsByUserID :many
SELECT 
    p.id, p.name, p.created_at, p.updated_at,
    pm.id, pm.project_id, pm.user_id, pm.role, pm.created_at
FROM project_members pm
JOIN projects p 
    ON p.id = pm.project_id
WHERE pm.user_id = $1
ORDER BY p.created_at DESC
`

type GetProjectsByUserIDRow struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	ID_2        int64            `json:"id_2"`
	ProjectID   int64            `json:"project_id"`
	UserID      int64            `json:"user_id"`
	Role        ProjectRole      `json:"role"`
	CreatedAt_2 pgtype.Timestamp `json:"created_at_2"`
}

func (q *Queries) GetProjectsByUserID(ctx context.Context, userID int64) ([]GetProjectsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getProjectsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectsByUserIDRow
	for rows.Next() {
		var i GetProjectsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID_2,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
