// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package repositery

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (type, user_id, project_id, expires_at) VALUES ($1, $2, $3, $4) RETURNING id, type, user_id, project_id, created_at, expires_at
`

type CreateRequestParams struct {
	Type      RequestsType `json:"type"`
	UserID    int64        `json:"user_id"`
	ProjectID *int64       `json:"project_id"`
	ExpiresAt time.Time    `json:"expires_at"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.Type,
		arg.UserID,
		arg.ProjectID,
		arg.ExpiresAt,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.UserID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteRequestByID = `-- name: DeleteRequestByID :exec
DELETE FROM requests WHERE id = $1
`

func (q *Queries) DeleteRequestByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRequestByID, id)
	return err
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT id, type, user_id, project_id, created_at, expires_at FROM requests WHERE id = $1
`

func (q *Queries) GetRequestByID(ctx context.Context, id uuid.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestByID, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.UserID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
